In [1]:
# 배열 만들기

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
print(np.array([3,1.4,2,3,4.5]))
# numpy의 array는 단일 데이터 타입
# 정수, 실수 >> 실수 변경됨

[3.  1.4 2.  3.  4.5]


In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
print(np.array([1,2,3,4]))
print(np.array([1,2,3,4],dtype = float))
# dtype 옵션 : data type 명시

print()
arr = np.array([1,2,3,4],dtype = float)
print(arr)
print(arr.dtype)

# astype() : 데이터 타입 변경 
print(arr.astype(int))

[1 2 3 4]
[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]


In [63]:
# np.zeros()
np.zeros(10,dtype = int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
# np.ones()
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
# np.arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
# np.linspace(): n등분
np.linspace(0,1,5)
# 0부터 1까지 5등분

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [67]:
# 난수 활용, 배열 만들기
np.random.random((2,2))
# 0~1 사이 균일 분포 난수 생성
# (2,2) : size >> 튜플 형태로 매개변수로 받아서 난수 생성

array([[0.70437174, 0.79454311],
       [0.80999637, 0.57800487]])

In [68]:
# np.random.random()과 np.random.rand()의 차이
np.random.rand(2,2)
# 0~1 사이 균일 분포 난수 생성
# 직접 차원(2,2)인수 넣어줌

array([[0.39426013, 0.41237802],
       [0.5159886 , 0.95486138]])

In [69]:
# np.random.normal()
np.random.normal(0, 1, (2,2))
# normal(평균, 표준편차, 매개변수(튜플))
# 정규분포 형태, 매개변수를 튜플로 받아서 난수 생성

array([[-0.1136943 ,  1.68256982],
       [-0.09769443, -0.98380447]])

In [70]:
np.random.randn(2,2)
# 2*2 크기의 배열을 직접 생성

array([[-0.98360699,  0.52072005],
       [-0.79842871, -0.33311635]])

In [71]:
np.random.randint(0,10,(2,2))
# 0에서부터 9까지 숫자 범위에서 
# 정수로 이루어진 (2,2) 행렬 생성
# 숫자 범위를 다 제시함. 따라서 size를 명시 안해도 됨

array([[4, 6],
       [9, 2]])

In [72]:
# 배열의 기초
np.random.randint(10, size=(3,4))
# 10: 최댓값, 명시 안하면 최솟값 0

array([[8, 1, 7, 7],
       [7, 2, 6, 2],
       [2, 8, 8, 1]])

In [7]:
# np.random.randint(10, (3,4))
# 값의 범위를 10 단일의 값으로 표현할 때, 

array([[2, 0, 2, 2],
       [5, 7, 8, 4],
       [5, 4, 7, 6]])

In [73]:
x = np.random.randint(10, size=(3,4))

print(x.ndim)   # 2>> 2차원
print(x.shape)  # (3,4)행렬(형태)
print(x.size)   # 12 >> 크기 (원소의 개수)
print(x.dtype)  # int32 (정수)

2
(3, 4)
12
int32


In [74]:
# index과 slicing
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
# indexing
a =np.arange(7)

print(a[3])
print(a[-3])


3
4


In [9]:
# slicing

print(a)
print()
print(a[1:4])
print()
print(a[1:])
print()
print(a[::2])   # interval 2칸씩
print()
print(a[::-1])  # 역순(***)

[0 1 2 3 4 5 6]

[1 2 3]

[1 2 3 4 5 6]

[0 2 4 6]

[6 5 4 3 2 1 0]


In [77]:
# reshape (형태 변경)(****)

x = np.arange(8)
print(x)
print()

print(x.shape)  # 1차원 (8개 원소)
print()

x2 = x.reshape((2,4))
print(x2)    # 2차원 (2,4) 행렬로 변환
print(x2.shape)

[0 1 2 3 4 5 6 7]

(8,)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [78]:
# 이어 붙이고 나누기 작업

# 이어 붙이기 >> concatenate : array 이어 붙임

x1 = np.array([0,1,2])
x2 = np.array([3,4,5])

print(x1)
print()
print(x2)
print()

print(np.concatenate([x1,x2]))

[0 1 2]

[3 4 5]

[0 1 2 3 4 5]


In [79]:
# concatenate >> axis 축 기준 이어 붙이기

m = np.arange(4).reshape(2,2)

print(m)
print()
print(np.concatenate([m,m]))
print()
print(np.concatenate([m,m],axis=0))
# axis=0  defalut 값

print()
print(np.concatenate([m,m],axis=1))

[[0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]


In [80]:
# 나누기 split
np.arange(16).reshape(4,4)

m = np.arange(16).reshape(4,4)

print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [81]:
print(np.split(m,[3],axis=0))
# 3행을(axis = 0) 기준으로 나눠주라는 의미

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [82]:
np.split(m,[3],axis=0)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [83]:
m1, m2 = np.split(m,[3],axis=0)

print(m1)
print()
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [84]:
print(np.split(m,[3],axis=1))

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [85]:
m1, m2 = np.split(m,[3],axis=1)

print(m1)
print()
print(m2)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [18]:
# array의 모든 원소에 5를 더하는 함수 생성

def 더하기_5(values):
    np.empty(len(values))
    
    for i in range(len(values)):
        output = values[i] + 5
    return output

values = np.random.randint(1,10, size = 5)

print(values)
print()
print(더하기_5(values))

[2 7 7 1 1]

6


In [20]:
# 스스로 해보기
# array의 모든 원소에 5를 더하는 함수 생성
def 더하기_5(value):
    for i in range(len(value)):
        value[i] = value[i]+5
    return value    

value = np.random.randint(1,10,5)
# value = np.random.randint(1,10,size = 5)
print(value)
print()
print(더하기_5(value))

[8 5 8 6 4]

[13 10 13 11  9]


In [13]:
# cf)
value = np.random.randint(1,10,5)
print(value)
print(value[1])
value[1]=value[1]+5
print(value)

[4 9 1 9 1]
9
[ 4 14  1  9  1]


In [21]:
# loop vs numpy

big_arr = np.random.randint(1,10,size = 100000)

더하기_5(big_arr)

array([ 8, 12, 14, ...,  7, 11,  6])

In [ ]:
big_arr + 5 # brodcasting되어 계산 >> 훨씬 빠름 

In [23]:
np.empty(5)
# 5개 원소를 가진 1차원 배열 생성
# (초기화는 되어 있지 않음)
# > 여기에 출력되는 값은 메모리에 이미 존재한 임의의 값으로 배열 채움

array([3. , 1.4, 2. , 3. , 4.5])

In [ ]:
# 기본 연산 

np.arange(4)

In [24]:
x= np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*5)
print(x/5)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [25]:
# 행렬 간 연산
x = np.arange(4).reshape((2,2))

y = np.random.randint(10,size=(2,2))
print(x)
print()
print(y)
print()
print(x+y)
print()
print(x-y)

[[0 1]
 [2 3]]

[[5 0]
 [2 9]]

[[ 5  1]
 [ 4 12]]

[[-5  1]
 [ 0 -6]]


In [98]:
# 브로드캐스팅(broadcating)

print(x)
print()
print(x+5)
# 5씩 증가됨을 확인

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [100]:
# 집계 함수

np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
x = np.arange(8).reshape(2,4)

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(sum(x))

28
0
7
3.5
[ 4  6  8 10]


In [103]:
# axis 사용, 집계하기

print(x)
print()
print(np.sum(x,axis=0))
print()
print(np.sum(x,axis=1))

[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [104]:
# 마스킹(masking) 연산 (조건 연산자 >> True, False)

np.arange(5)

array([0, 1, 2, 3, 4])

In [106]:
x = np.arange(5)
print(x<3)
print()
print(x>5)

[ True  True  True False False]

[False False False False False]


In [107]:
condition = (x<3)
x[condition]

array([0, 1, 2])