In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
print(arr1)

print(type(arr1))
print(arr1.shape) # 1 차원 


[1 2 3]
<class 'numpy.ndarray'>
(3,)
int32


In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(type(arr2))
print(arr2)
print(arr2.shape)   # (2,3) 행렬 >> 2차원

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
arr3 = np.array([[1,2,3]])

print(type(arr3))
print(arr3.shape)   # (2,3) 행렬 >> 2차원 

<class 'numpy.ndarray'>
(1, 3)


In [16]:
# ndim (number of dimension) 차원을 출력해줌
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2


In [17]:
# arange : array + range

np.arange(3)

array([0, 1, 2])

In [18]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [20]:
# 넘파이 배열 초기화

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
one_a = np.ones((3,4))

In [ ]:
# zeros_like()

# > one_a 나 one_b 동일한 0으로 채워진 배열 생성 

In [26]:
np.zeros_like(one_a)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
one_b = np.array([[1,2,3],[4,5,6]])
print(one_b)

[[1 2 3]
 [4 5 6]]


In [28]:
print(np.zeros_like(one_b))

[[0 0 0]
 [0 0 0]]


In [31]:
# np.full, np.random

# np.full
# 4*3 행렬 배열을 생성 >> 모든 요소를 특정 값으로 채움
print(np.full((4,3), 9))
print()
print(np.full((4,3), 5))

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [40]:
# random은 행렬구조로 괄호가 있음
# rand와의 차이점

# np.random()

np.random.seed(100)
# 1
print(np.random.random((3,4)))
# (3,4) 튜플 형태로 인자로 입력됨
# 0-1 사이 난수 성색

# 2
print()
print(np.random.rand(3,4))
# np.random.rand 난수 생성
# 마이너스 값x

#3
print()
print(np.random.randn(3,4))
# np.random.randn 난수 생성
# 평균 0, 표준편차 1 >> 표준화(x-x_bar)/std

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]

[[0.18532822 0.10837689 0.21969749 0.97862378]
 [0.81168315 0.17194101 0.81622475 0.27407375]
 [0.43170418 0.94002982 0.81764938 0.33611195]]

[[-0.43813562 -1.11831825  1.61898166  1.54160517]
 [-0.25187914 -0.84243574  0.18451869  0.9370822 ]
 [ 0.73100034  1.36155613 -0.32623806  0.05567601]]


In [43]:
np.random.rand(3,4,2)

array([[[0.97500649, 0.88485329],
        [0.35950784, 0.59885895],
        [0.35479561, 0.34019022],
        [0.17808099, 0.23769421]],

       [[0.04486228, 0.50543143],
        [0.37625245, 0.5928054 ],
        [0.62994188, 0.14260031],
        [0.9338413 , 0.94637988]],

       [[0.60229666, 0.38776628],
        [0.363188  , 0.20434528],
        [0.27676506, 0.24653588],
        [0.173608  , 0.96660969]]])

In [46]:
# np.eye(): 항등 행렬
#행렬 A, A*I = A

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
A = np.array([[2,4,1,5], 
              [8,1,3,4],
              [5,6,7,8],
              [1,2,3,4]])

print(A)
print()

I = np.eye(4)
print(I)
print()

print(A @ I)

[[2 4 1 5]
 [8 1 3 4]
 [5 6 7 8]
 [1 2 3 4]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[2. 4. 1. 5.]
 [8. 1. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]]


In [57]:
B = np.array([[2,4], 
              [8,1]])

print(B)
print()

I = np.eye(2)
print(I)
print()

print(B @ I)

[[2 4]
 [8 1]]

[[1. 0.]
 [0. 1.]]

[[2. 4.]
 [8. 1.]]


In [2]:
# 넘파이 배열 크기 변형
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr = np.arange(12)
print(arr)
print()
print(len(arr))
print()
arr2 = arr.reshape(3,-1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

12

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
arr.reshape(4,-1, order = 'F')
# order = 'F' : 값을 열부터 채워 넣음

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
arr1 = np.arange(10)
print(arr1)

# 컬럼을 5개 행은 끝에 맞춰
arr2 = arr1.reshape(-1,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 5)


In [12]:
arr3 = np.arange(12)
print(arr3) # 1차원
print()

arr4 = arr3.reshape(2,3,2)
print(arr4) # 3차원


[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [14]:
arr5 = arr3.reshape(2,3,2,order = 'F')
print(arr5) # 3차원

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [16]:
print(arr5.ndim)
print(arr5.shape)
# (2, 3, 2): 2개가 있다. 뭐가? (3,2) 행렬이

3
(2, 3, 2)


In [18]:
# 1차원으로 변환
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# 넘파이 배열 데이터 추출하기

# 1) indexing
np.arange(1,10)

arr1 = np.arange(1,10)
print(arr1)


[1 2 3 4 5 6 7 8 9]


In [54]:
print(arr1[2])
print(arr1[-2])

3
8


In [55]:
arr2 = arr1.reshape(3,3)   #arr1.reshape(3,-1)
print(arr2)

print()
print(arr2[0,0])
print(arr2[-1,-2])
print(arr2[-1,:-1]) # 리스트로 나옴

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
8
[7 8]


In [1]:
print(arr1)
print()

arr2 = arr1[0:3]
print(arr2)
print()

arr3 = arr2[1:]
print(arr3)

arr4 = arr1.reshape(3,3)
print(arr4)

NameError: name 'arr1' is not defined

In [57]:
# 슬라이싱
print(arr4)
print()

print(arr4[:2,:2])
print(arr4[1:2,:3])
print(
print(arr4[:2, 1:])
)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]
[[4 5 6]]
[[2 3]
 [5 6]]
None


In [40]:
# 내적(dot product)

arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[7,8],[9,10],[1,2]])

print(arr1)
print()
print(arr2)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [ 1  2]]


In [41]:
arr1 @ arr2

array([[28, 34],
       [79, 94]])

In [42]:
np.dot(arr1, arr2)
# arr1 @ arr2 동일 값

array([[28, 34],
       [79, 94]])

In [45]:
print(arr1)
# arr1 @ arr1
# (2*3)@(3*2)

[[1 2 3]
 [4 5 6]]


In [48]:
# 전치 행렬

print(arr)
print(arr1.T)

print(arr1 @ arr1.T)
print()
print(np.dot(arr1,arr1.T))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]

[[14 32]
 [32 77]]


In [50]:
print(arr1)
print()
print(arr1.T)
print()
print(np.transpose(arr1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [58]:
# 넘파이 이용, 기술 통계

x = np.array([18,26,52,-54,64,15])
len(x)

6

In [60]:
print(np.mean(x))   # 평균
print(np.var(x))    # 분산: 퍼진 정도
print(np.std(x))   # 표준편차: 평균에서 떨어진 정도
37.64047762124646*37.64047762124646

20.166666666666668
1416.8055555555557
37.64047762124646


1416.8055555555557

In [63]:
print(x)
print()

print(np.max(x))
print()

print(np.min(x))
print()

print(np.median(x))
print()

[ 18  26  52 -54  64  15]

64

-54

22.0



In [64]:
x.sort()

In [65]:
x

array([-54,  15,  18,  26,  52,  64])

In [66]:
# 중위수 어떻게 구해지는지
(18+26)/2

22.0

In [68]:
# 사분위 수
print(np.percentile(x,25))
print(np.percentile(x,50))  # 중위수   
print(np.percentile(x,75))

15.75
22.0
45.5
